/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalistaRouteImport } from './routes/analista'
import { Route as CarteraRouteImport } from './routes/cartera'
import { Route as LigasRouteImport } from './routes/ligas'
import { Route as ValorRouteImport } from './routes/valor'
import { Route as LigasSlugRouteImport } from './routes/ligas.$slug'
import { Route as PartidoIdRouteImport } from './routes/partido.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaRoute = AnalistaRouteImport.update({
  id: '/analista',
  path: '/analista',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteraRoute = CarteraRouteImport.update({
  id: '/cartera',
  path: '/cartera',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasRoute = LigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorRoute = ValorRouteImport.update({
  id: '/valor',
  path: '/valor',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasSlugRoute = LigasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LigasRoute,
} as any)
const PartidoIdRoute = PartidoIdRouteImport.update({
  id: '/partido/$id',
  path: '/partido/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRoute
  '/cartera': typeof CarteraRoute
  '/ligas': typeof LigasRouteWithChildren
  '/valor': typeof ValorRoute
  '/ligas/$slug': typeof LigasSlugRoute
  '/partido/$id': typeof PartidoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRoute
  '/cartera': typeof CarteraRoute
  '/ligas': typeof LigasRouteWithChildren
  '/valor': typeof ValorRoute
  '/ligas/$slug': typeof LigasSlugRoute
  '/partido/$id': typeof PartidoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analista': typeof AnalistaRoute
  '/cartera': typeof CarteraRoute
  '/ligas': typeof LigasRouteWithChildren
  '/valor': typeof ValorRoute
  '/ligas/$slug': typeof LigasSlugRoute
  '/partido/$id': typeof PartidoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analista'
    | '/cartera'
    | '/ligas'
    | '/valor'
    | '/ligas/$slug'
    | '/partido/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analista'
    | '/cartera'
    | '/ligas'
    | '/valor'
    | '/ligas/$slug'
    | '/partido/$id'
  id:
    | '__root__'
    | '/'
    | '/analista'
    | '/cartera'
    | '/ligas'
    | '/valor'
    | '/ligas/$slug'
    | '/partido/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalistaRoute: typeof AnalistaRoute
  CarteraRoute: typeof CarteraRoute
  LigasRoute: typeof LigasRouteWithChildren
  ValorRoute: typeof ValorRoute
  PartidoIdRoute: typeof PartidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analista': {
      id: '/analista'
      path: '/analista'
      fullPath: '/analista'
      preLoaderRoute: typeof AnalistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartera': {
      id: '/cartera'
      path: '/cartera'
      fullPath: '/cartera'
      preLoaderRoute: typeof CarteraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas': {
      id: '/ligas'
      path: '/ligas'
      fullPath: '/ligas'
      preLoaderRoute: typeof LigasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valor': {
      id: '/valor'
      path: '/valor'
      fullPath: '/valor'
      preLoaderRoute: typeof ValorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas/$slug': {
      id: '/ligas/$slug'
      path: '/$slug'
      fullPath: '/ligas/$slug'
      preLoaderRoute: typeof LigasSlugRouteImport
      parentRoute: typeof LigasRoute
    }
    '/partido/$id': {
      id: '/partido/$id'
      path: '/partido/$id'
      fullPath: '/partido/$id'
      preLoaderRoute: typeof PartidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LigasRouteChildren {
  LigasSlugRoute: typeof LigasSlugRoute
}

const LigasRouteChildren: LigasRouteChildren = {
  LigasSlugRoute: LigasSlugRoute,
}

const LigasRouteWithChildren = LigasRoute._addFileChildren(LigasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalistaRoute: AnalistaRoute,
  CarteraRoute: CarteraRoute,
  LigasRoute: LigasRouteWithChildren,
  ValorRoute: ValorRoute,
  PartidoIdRoute: PartidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
